[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
p1 = "8RpJAbzQUK6EKsai1QCRKDctwLXMiwMkZkVhCBzKrzxZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "solana_wallets/wallet_0.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
