[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
message_board = "2naBoSzVrc8HusiE1wsWW11WD3p2DfxZxc62gAvEUtNW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "wallets/wallet2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
