[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
p21 = "FKeGW2KYKDMUUhJpFb5QJeLXBv5RzVQM4fcEWKGD997d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./solana_wallets/wallet_0.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
