[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
t1 = "B1mwXwsaY8nPUTJ3coexanu7Dp8nFsmZuFtGL3iWuntD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./solana_wallets/wallet_0.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
